apiVersion: v1
data:
  DB_HOST: ZGJfY29udA==
  DB_NAME: dGVzdF9kYg==
  DB_PASSWORD: cm9vdA==
  DB_PORT: MzMwNg==
  DB_USER: cm9vdA==
  MYSQL_DATABASE: dGVzdF9kYg==
  MYSQL_ROOT_PASSWORD: cm9vdA==
kind: Secret
metadata:
  name: django-app-secret
  namespace: notes-app
type: Opaque
